version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.1-apache
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo pdo_mysql
      - checkout
      - run:
          name: Display PHP information
          command: php -v
      - run:
          name: Starting Apache
          command: service apache2 status || service apache2 start
      - run:
          name: Test API Homepage status code
          command: curl -f -i localhost
